<?php

namespace App\Transaction\Constants;

final class PermissionConstant
{
  public const APP_PERMISSION = [
    'access-admin-panel',
    'activity-create',
    'activity-edit',
    'activity-view',
    'activity-soft-delete',
    'activity-delete',
    'checklist-create',
    'checklist-edit',
    'checklist-delete',
    'checklist-soft-delete',
    'checklist-view',
    'company-create',
    'company-edit',
    'company-view',
    'company-soft-delete',
    'company-delete',
    'project-create',
    'project-edit',
    'project-view',
    'project-soft-delete',
    'project-delete',
    'address-create',
    'address-edit',
    'address-view',
    'address-soft-delete',
    'address-delete',
    'person-create',
    'person-edit',
    'person-view',
    'person-soft-delete',
    'person-delete',
    'finance-acceptance',
    'finance-payment',
    'user-role-create',
    'user-role-edit',
    'user-role-assign',
    'user-role-view',
    'user-role-delete',
    'project-assign-person',
    'project-assign-address',
    'project-assign-vehicle',
    'vehicle-create',
    'vehicle-edit',
    'vehicle-view',
    'vehicle-delete',
    'vehicle-condition-view',
  ];
}